version: 1.0.{build}
image: Visual Studio 2019
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: >-
    dotnet restore Inshapardaz.SpellChecker.sln

    dotnet test ./tests/Inshapardaz.SpellChecker.Tests/Inshapardaz.SpellChecker.Tests.csproj

    dotnet build Inshapardaz.SpellChecker.sln -c Release

    dotnet pack .\src\Inshapardaz.SpellChecker\Inshapardaz.SpellChecker.csproj /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**\*.nupkg'
  name: NugetPackage
deploy:
- provider: NuGet
  api_key:
    secure: JQqEB5jgnPWVtZTocVWQmYj8bjccZgasZuPdrQ7qg7sU9T8MD9JtOonM2xN1AvDC
  artifact: /.*\.nupkg/
